
name: 'prism'
version: '0.1.0'
config-version: 2

profile: 'prism'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

seeds:
  prism:
    schema: raw

models:
  prism:
    # Config for all models
    materialized: view

    staging:
      materialized: view
      schema: staging

    intermediate:
      materialized: ephemeral
      schema: intermediate

    mart:
      materialized: table
      schema: mart
