ops:
  score_members_aca:
    config:
      claims_view: dbt_raw.claims_2024_9months
      enrollments_view: dbt_raw.raw_enrollments
      members_view: dbt_raw.raw_members
      invalid_gender: skip
      diy_model_year: "2024"
      member_age_basis_year: "2024"
      run_description: "Lag Analysis 2024 (9-month runout)"

resources:
  database:
    config: "dev"
