ops:
  dagster_runs_outputs__risk_scores:
    config:
      claims_view: main_raw.claims_2023_3months
      enrollments_view: main_raw.raw_enrollments_2023
      members_view: main_raw.raw_members_2023
      invalid_gender: skip
      diy_model_year: "2023"
      member_age_basis_year: "2023"
      run_description: "Lag Analysis 2023 (3-month runout)"

resources:
  database:
    config: "dev"
