ops:
  score_members_aca:
    config:
      claims_view: dbt_raw.claims_2021_3months
      enrollments_view: dbt_raw.raw_enrollments
      members_view: dbt_raw.raw_members
      invalid_gender: skip
      diy_model_year: "2021"
      member_age_basis_year: "2021"
      run_description: "Lag Analysis 2021 (3-month runout)"

resources:
  database:
    config: "dev"
