select
    member_id,
    first_name,
    last_name,
    dob,
    gender,
    email,
    phone,
    street,
    city,
    state,
    zip,
    fpl_ratio,
    hios_id,
    plan_network_access_type,
    'Silver' as plan_metal,
    age_group,
    region,
    enrollment_length_continuous,
    clinical_segment,
    general_agency_name,
    broker_name,
    sa_contracting_entity_name,
    call_count,
    app_login_count,
    web_login_count,
    new_member_in_period,
    member_used_app,
    member_had_web_login,
    member_visited_new_provider_ind,
    high_cost_member,
    mutually_exclusive_hcc_condition,
    geographic_reporting,
    wisconsin_area_deprivation_index,
    ra_mm,
    year
from {{ ref('raw_members') }}
where cast(year as integer) = 2024
